add keyConcepts for Controlled Vocabulary
italia/daf-ontologie-vocabolari-controllati pull request #152
Opened 2021-12-13 11:23 UTC by SrinivasanTarget

@ioggstream @giorgialodi ping

2021-12-13 14:05 UTC, giorgialodi requested changes

2021-12-13 14:05 UTC, giorgialodi commented on VocabolariControllati/classifications-for-accommodation-facilities/accommodation-star-rating/accommodation-star-rating.ttl
> +@prefix ndc: <https://w3id.org/italia/onto/ndc-profile/> .
@SrinivasanTarget the prefix of NDC is no longer this one but https://w3id.org/italia/onto/NDC/. It should be corrected in all CVs

2021-12-13 14:23 UTC, ioggstream commented
@giorgialodi we need to regenerate all rdf+xml, jsonld files, right?

2021-12-13 14:26 UTC, giorgialodi commented
> @giorgialodi we need to regenerate all rdf+xml, jsonld files, right?

hmmm, you are right because I see here the intervention only in the turtle files.

2021-12-13 14:32 UTC, ioggstream commented
@giorgialodi I'm doing the fixes..

2021-12-14 09:12 UTC, ioggstream commented
@SrinivasanTarget  I'll merge once you merge :P

2021-12-14 10:25 UTC, SrinivasanTarget commented
@ioggstream your changes are merged. thanks.

2021-12-14 11:13 UTC, giorgialodi approved these changes
The prefix for NDC is not correct. I see a lot of other intervention not only for the ndc profile and keyConcepts here regarding spaces. @ioggstream what's that? Anyway, it seems to me ok anyway, so you can merge.

2021-12-14 11:47 UTC, ioggstream commented
just trimming EOL/EOF spaces in edited files.

2021-12-14 11:47 UTC, merged