Fix: #172. Invalid blank field terminates URI.
italia/daf-ontologie-vocabolari-controllati pull request #183
Opened 2022-07-22 12:38 UTC by ioggstream

## This PR

- fixes wrong space in URI
- according to https://datatracker.ietf.org/doc/html/rfc3986 a blank char, either in ascii or %-encoded as %20 in an URI path segment terminates the URI.

Reading the taxonomy, the correct value is the one used in the PR since the other was already defined.

2022-07-22 12:40 UTC, ioggstream commented
@marco-deligios puoi darci un feedback qui please? La modifica in un modo o nell'altro va fatta perché sintatticamente l'URL non è fungibile da un tool conforme alle specifiche.

2022-07-22 12:50 UTC, giorgialodi commented
Sorry but that URI is valid and I do not understand the point. %20 is added to encode the space. So the issue here is to understand whether that identifier contains two or only one value. I will check this, but changing a persistent URI is a critical operation to avoid as much as possible.

2022-07-25 07:40 UTC, marco-deligios commented
è passato molto tempo, non ricordo la discussione e non la trovo... mi aiutate?

2022-07-25 16:31 UTC, ioggstream commented
@marco-deligios c'è una entry fatta così: la chiave contiene due identificativi separati da spazio

```
040102 040201,Obbligo di pubblicazione concernente i titolari di incarichi dirigenziali,Comuni,204
```

Poiché 04102 è già assegnato, l'ipotesi è che ci sia stato un typo in fase di editing

```
040201,Obbligo di pubblicazione concernente i titolari di incarichi dirigenziali,Comuni,204
```

La PR sostituisce l'id `04102 040201` con `040201` . Che tu sappia, l'id `040201` è quello corretto ?
Ci sono altri id con spazi in mezzo (mi risulta di no).

2022-07-26 10:46 UTC, marco-deligios commented
Ciao Roberto, mi devi perdonare, ma mi è difficile rientrare dopo così tanto tempo.
Riguardando i miei appunti ho parecchi dubbi sulla corrispondenza tra la tabella ANAC e [transparency-obligation]
Se vuoi possiamo fare una call per discuterne

2022-08-02 09:47 UTC, ioggstream commented
@giorgialodi @marco-deligios sappiamo chi sta utilizzando quei codici?

2022-08-03 13:50 UTC, giorgialodi commented
> @giorgialodi @marco-deligios sappiamo chi sta utilizzando quei codici?

Non lo so ma guardate quello che ho scritto sopra. Ho trovato come modificare l'URI. Attenzione, il problema non è il %20 nell'URI che è ammesso in presenza di spazi, ma il problema è che un pezzo di quel numero finale non esiste nel vocabolario in questione. Detta in altri termini, cambiare l'URI si può perché non è definito da nessuna parte e quindi è appeso, ma il cambio di URI è come vi ho scritto sopra e non come suggerito nella PR: quell'URI della PR non esiste nel vocabolario transparency-obligation, se ho ricostruito bene il tutto.

2022-08-03 13:53 UTC, giorgialodi requested changes

2022-08-03 13:53 UTC, giorgialodi commented on VocabolariControllati/classifications-for-transparency/transparency-obligation/transparency-obligation-organization.ttl
> +<https://w3id.org/italia/controlled-vocabulary/classifications-for-transparency/transparency-obligation/040201>
@ioggstream the point here is not that URI includes %20 which is admitted as I've already written. The error here is that the URI with the %20 is not defined in the transparency-obligation vocabulary. Therefore, the operation of revision of the URI can be done; it should be revised in this way:

https://w3id.org/italia/controlled-vocabulary/classifications-for-transparency/transparency-obligation/040102%20040201 --> it should be replaced by https://w3id.org/italia/controlled-vocabulary/classifications-for-transparency/transparency-obligation/040102 (and NOT the one you suggest with this PR). However, the strange thing here is that 040201 is not defined in transparency obligation. 

In essence, I would proceed as indicated in this comment, replacing with 040102  because the rest you propose does not exist.

2022-08-03 13:53 UTC, giorgialodi commented on VocabolariControllati/classifications-for-transparency/transparency-obligation/transparency-obligation-administration-category.csv
> +040201,Obbligo di pubblicazione concernente i titolari di incarichi dirigenziali,Comuni,204
qui dovrebbe essere 040102 e non 040201

2023-11-24 15:00 UTC, giorgialodi commented
Se non ricordo male questa cosa è stata fixata in altro modo per via dell'errore che è stato rilevato a suo tempo e qui documentato. Chiuderei questa PR senza fare merge @bfabio  @mfortini @Clou-dia

2023-11-24 15:34 UTC, closed without merging