BCS 1.0 - Beni Culturali Standard
italia/daf-ontologie-vocabolari-controllati pull request #205
Opened 2023-02-19 16:44 UTC by tmancinelli

La Beni Culturali Standard è un'etichetta per la pubblicazione delle riproduzioni digitali dei beni culturali del Ministero della Cultura. Potete leggere i termini e le condizioni nelle linee guida di circolazione e riuso: https://docs.italia.it/italia/icdp/icdp-pnd-circolazione-riuso-docs/it/v1.0-giugno-2022/testo-etichetta-BCS.html#etichetta-beni-culturali-standard-bcs

2023-03-02 15:27 UTC, mfortini requested changes
Alcune osservazioni.

La nuova licenza dovrebbe seguire la strutturazione del vocabolario anche per l’URI ad essa assegnata. Al momento l’URI è l’URL della pagina web su [dati.gov.it](http://dati.gov.it/)
La codifica per le URI utilizzata è la seguente: `https://w3id.org/italia/controlled-vocabulary/licences/B210_BSC10`, da usare poi nei vari livelli della gerarchia del vocabolario. `B210` sarebbe il codice nel vocabolario che gli viene associato (B.2.10).
(Questo abilita anche la visualizzazione della licenza nel vocabolario complessivo, mediante visualizzatori come LodView attualmente utilizzati da [schema.gov.it](http://schema.gov.it/) (catalogo nazionale ontologie, vocabolari controllati e schemi di dati).)

Siccome il vocabolario non vuole modellare i diritti delle singole licenze, ma fornire una lista controllata di nomi di licenze di un certo tipo, la specifica mediante creative commons ontology dei vari requirement sbilancia questa licenza rispetto alle altre nel vocabolario, rendendolo non più uniforme.
Trattandosi di informazioni molto importanti, si suggeriscono due possibilità:
1) inserire tutti i permessi e i requisiti nella `skos:definition`, perché di fatto è la definizione di quella licenza
2) utilizzare una proprietà generica come `skos:note` oppure anche `skos:scopeNote` perché i permessi definiscono di fatto lo scope della licenza.
Inserire nella definizione del concetto di questa licenza la proprietà `clv:hasrankOrder "3"` ; per uniformità con gli altri livelli.
Modificare lo `skos:notation` che deve essere  `"B.2.10"`, ossia il codice assegnato alla licenza nel vocabolario e non l’acronimo della licenza con la sua versione.

Infine si segnala l'opportunità di fare riferimento al testo della licenza  (attualmente valorizzato con la proprietà `dcatapit:referenceDoc`)  inserendolo in un'apposita pagina sul sito del Ministero della Cultura.

2023-03-21 08:38 UTC, tmancinelli commented
Ho applicato i commenti suggeriti. 

Riguardo alla URI `https://w3id.org/italia/controlled-vocabulary/licenses/B210_BCS10` vorrei sapere la procedura per crearla.

Inoltre, abbiamo scelto dati.gov.it per essere più inclusivi e rivolgerci anche a enti e altri soggetti al di fuori del Ministero della Cultura.

2023-05-11 09:47 UTC, mfortini commented
Nel commento precedente avevamo indicato la licenza come "chiusa-no opere derivate". Da un'ulteriore verifica, riteniamo più corretto classificarla come "licenza chiusa-per uso non commerciale (a meno delle autorizzazioni)". Di conseguenza, la codifica per le URI da usare diventa la seguente: `https://w3id.org/italia/controlled-vocabulary/licences/B117_BSC10`, da usare poi nei vari livelli della gerarchia del vocabolario. In questo caso, `B117` è il codice nel vocabolario che gli viene associato (`B.1.17` da usare nella proprietà `skos:notation`). Ossia B —> Licenza Chiusa, B.1 —> Solo Uso non Commerciale e 17 prosegue la numerazione già disponibile.
Non si deve preoccupare dell’URI: quando si farà merge e il vocabolario aggiornato sarà presente sullo sparql endpoint di schema.gov.it l’URI si risolverà per via della gestione degli URI di questo repo.
Per quanto riguarda la presenza su dati.gov.it ci risultava anomala una pagina dedicata a una licenza chiusa in un portale di dati aperti che promuove solo licenze aperte. Tuttavia, se questo è stato concordato con AGID, nulla osta.

Le chiediamo quindi solo di rivedere l’URI come sopra indicato mantenendo ovviamente tutti i suggerimenti già forniti. Grazie

2023-06-13 09:39 UTC, ioggstream commented
@mfortini vanno sbloccati i workflow credo, altrimenti mancano i test.

2023-09-12 12:20 UTC, tmancinelli commented
@mfortini @ioggstream Ci sono novità? Possiamo fare il merge di questa pull request? E' ferma dal 13 giugno...

2023-09-15 09:27 UTC, merged