Valorizzazione del campo rightsHolder per issue #263
italia/daf-ontologie-vocabolari-controllati pull request #270
Opened 2024-05-07 13:37 UTC by stefanopareti

Valorizzazione del campo rightsHolder per l'ontologia DCAT-AP_IT  per issue #263

2024-05-17 09:38 UTC, bfabio commented
@stefanopareti grazie.

Inizialmente pensavamo che servisse anche [quest'altra PR,](https://github.com/italia/daf-ontologie-vocabolari-controllati/pull/264) e che fosse stata chiusa per sbaglio , ma abbiamo notato che ha le stesse modifiche.

Puoi aggiornare anche gli altri due formati dell'ontologia (`jsonld` e `rdf`)? Potete farlo direttamente su questa PR.

2024-06-17 10:49 UTC, giorgialodi requested changes
foaf:label should be corrected everywhere.

2024-06-17 10:49 UTC, giorgialodi commented on Ontologie/DCAT/latest/DCAT-AP_IT.jsonld
> +   "http://xmlns.com/foaf/0.1/label" : [ {
What's foaf:label?

2024-06-17 10:49 UTC, giorgialodi commented on Ontologie/DCAT/latest/DCAT-AP_IT.jsonld
> +   "http://xmlns.com/foaf/0.1/label" : [ {
Here it is rdfs:label. It should be corrected. @Clou-dia @bfabio

2024-06-17 10:49 UTC, giorgialodi commented on Ontologie/DCAT/latest/DCAT-AP_IT.rdf
> +		<foaf:label xml:lang="it">Agenzia per l&apos;Italia Digitale</foaf:label>
Same here foaf:label is not correct

2024-06-17 11:06 UTC, Clou-dia commented on Ontologie/DCAT/latest/DCAT-AP_IT.jsonld
> +   "http://xmlns.com/foaf/0.1/label" : [ {
@stefanopareti

2024-06-18 13:02 UTC, giorgialodi commented
Ok, the problem has been fixed. @Clou-dia @bfabio

2024-06-18 13:49 UTC, merged